---
# tasks file for web
- name: Install required packages
  ansible.builtin.apt:
    name:
      - nginx
      - "php{{ web_apt_php_version }}-fpm"
    state: present
    update_cache: yes

- name: Deploy nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/website.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart nginx

- name: ensures /var/www/html dir exists
  ansible.builtin.file:
    path: "/var/www/html"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

# setting the www.conf .
- name: Set permissions on socket - owner
  ansible.builtin.lineinfile:
    dest: "/etc/php/{{ web_apt_php_version }}/fpm/pool.d/www.conf"
    regexp: '^;?listen.owner'
    line: "listen.owner = {{ web_php_owner }}"
  notify: Restart php-fpm

- name: Set permissions on socket - group
  ansible.builtin.lineinfile:
    dest: "/etc/php/{{ web_apt_php_version }}/fpm/pool.d/www.conf"
    regexp: '^;?listen.group'
    line: 'listen.group = {{ web_php_group }}'
  notify: Restart php-fpm

- name: Set permissions on socket - mode
  ansible.builtin.lineinfile:
    dest: "/etc/php/{{ web_apt_php_version }}/fpm/pool.d/www.conf"
    regexp: '^;?listen.mode'
    line: 'listen.mode = 0660'
  notify: Restart php-fpm

- name: Deploy index.php
  ansible.builtin.copy:
    src: index.php
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: "0644"
  notify:
    - Restart php-fpm

- name: Ensure php-fpm service is enabled and started
  ansible.builtin.service:
    name: php{{ web_apt_php_version }}-fpm
    state: started
    enabled: yes

- name: Ensure nginx service is enabled and started
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Deploy logrotate config for nginx logs
  ansible.builtin.copy:
    content: |
      /var/log/nginx/*log {
          daily
          missingok
          rotate 14
          compress
          delaycompress
          notifempty
          create 0640 www-data adm
          sharedscripts
          postrotate
              [ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`
          endscript
      }
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart nginx
